logging:
  path: C:/Users/Allan/Documents/TacoCloud
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        security: INFO
        
    
# server:
#  port: 8443
#  ssl:
#    key-password: 123456
#    key-store: src/main/resources/mykeys.jks
#    key-store-password: 123456
  
spring:
  datasource:
     username: root
     password: root
     url: jdbc:mysql://localhost:3306/taco?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
  profiles:
    active: thymeleaf-security
    
taco:
  orders:
    page-size: 10  
